Traceback (most recent call last):
  File "/home/user/Desktop/Python-Pereverzev/mod5/task4.py", line 31, in <module>
    raise Exception('Hello stderr.txt')
Exception: Hello stderr.txt
